name: Super-Linter

on: push 

jobs:
  super-lint:
    name: Lint based code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Super-Linter
        uses: github/super-linter@v4.10.1

        
